In [ ]:
#10.a. Implementation of word embedding - Bag of Words

from sklearn.feature_extraction.text import CountVectorizer
corpus=["I love machine learning",
        "Machine learning is fun",
        "I love programming"]

vectorizer=CountVectorizer()
X=vectorizer.fit_transform(corpus)

bow_matrix=X.toarray()
vocabulary=vectorizer.get_feature_names_out()
print("Bag of Words Matrix:")
print(bow_matrix)
print("\nVocabulary:")
print(vocabulary)

Bag of Words Matrix:
[[0 0 1 1 1 0]
 [1 1 1 0 1 0]
 [0 0 0 1 0 1]]

Vocabulary:
['fun' 'is' 'learning' 'love' 'machine' 'programming']


In [ ]:
#10.b. Implementation of word embedding - TF-IDF

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'I love programming in Python',
    'Python programming is fun',
    'I love coding in Python',

]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
tfidf_array = X.toarray()
feature_names = vectorizer.get_feature_names_out()

print("TF-IDF Representation:")
print(tfidf_array)

print("\nFeature Names (Words):")
print(feature_names)


for i, doc in enumerate(tfidf_array):
    print(f"\nDocument {i + 1}:")
    for j, score in enumerate(doc):
        if score > 0:
            print(f"{feature_names[j]}: {score:.4f}")

TF-IDF Representation:
[[0.         0.         0.52682017 0.         0.52682017 0.52682017
  0.40912286]
 [0.         0.5844829  0.         0.5844829  0.         0.44451431
  0.34520502]
 [0.63174505 0.         0.4804584  0.         0.4804584  0.
  0.37311881]]

Feature Names (Words):
['coding' 'fun' 'in' 'is' 'love' 'programming' 'python']

Document 1:
in: 0.5268
love: 0.5268
programming: 0.5268
python: 0.4091

Document 2:
fun: 0.5845
is: 0.5845
programming: 0.4445
python: 0.3452

Document 3:
coding: 0.6317
in: 0.4805
love: 0.4805
python: 0.3731
